version: '3.1'

services:
  mongo:
    image: mongo:4
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongo"
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=mongo"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=secret"

volumes:
  mongo-data: