version: '3.7'

services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.1.1
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    restart: always
    ports:
      - 8080:80
volumes:
  dbdata:
