version: "3.7"

services:
  PostgreSQL:
    image: postgres:9.6.23
    restart: always
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "PGDATA=/var/lib/postgresql/data"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5.6
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=postgres@example.com"
      - "PGADMIN_DEFAULT_PASSWORD=postgres"
      - "PGADMIN_LISTEN_PORT=80"
    ports:
      - "8082:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "PostgreSQL:pgsql-server"

volumes:
  postgres-data:
  pgadmin-data: